### ISSUE TITLE
Undefined is not a function

### ISSUE THREAD

**Issue by volkanunsal** [faradayio/tilesplash#10]
Another error:

```
TypeError: undefined is not a function
    at Object.<anonymous> (/Users/newuser/w/citiesense/api/tiles/index.js:6:3)
    at /Users/newuser/w/citiesense/api/tiles/node_modules/tilesplash/lib/index.js:402:22
```

Here is the code that causes it:

```javascript
var Tilesplash = require('tilesplash');
var app = new Tilesplash('postgis://postgres:@localhost:5432/dev');
app.layer('test_layer', function(req, res, tile, done){
  done(null, 'SELECT ST_AsGeoJSON(geometry) FROM parcels;');
});
app.server.listen(3000);
```

**Comment by volkanunsal** [comment]
I figured it might be that the API has changed since the first example, and I tried to use a callback function with `function(tile, render)`, and that throws a different error:

```javascript
  return new Promise(function(resolve, reject){
             ^
ReferenceError: Promise is not defined
```

Does this mean it depends on a newer version of Node? I'm on 0.10.35.

**Comment by volkanunsal** [comment]
Switched to the iojs-2.4.0. The error is different now:

```
SyntaxError: Unexpected token u
    at Object.parse (native)
    at /Users/newuser/w/citiesense/api/tiles/node_modules/tilesplash/lib/index.js:303:34
```

**Comment by volkanunsal** [comment]
Aha, I think I figured out that I needed to use the ` ST_Intersects(geometry, !bbox_4326!);` in my query. That was far from obvious to me just from reading the README.

**Comment by devTristan** [comment]
Tilesplash does in fact require a global Promise object, as you found. Older versions of node which don't come with this won't work unless you bring it in somehow.

You're right that the documentation is lacking here. It's looking for a column called `the_geom_geojson`.

The most efficient way to do this is by having two geometry columns, one in 4326 and one in 3857. Here's an example of a working query:

```sql
SELECT ST_AsGeoJSON(the_geom) as the_geom_geojson
FROM table
WHERE the_geom_webmercator && !bbox!
```

**Comment by volkanunsal** [comment]
Clever use of `&&`. I'm gonna look into adding a second column. Thanks!

**Comment by volkanunsal** [comment]
Actually, I have a question about `bbox_4326`. This seems to be creating a diamond shaped bounding box around the coordinate we pass with the x, y and z parameters –– I say diamond shaped because the returned endpoints appear to form a diamond: `[w, s, e, n]`. 

I haven't had much success in a few attempts to get the geometries around a central point, and I've tried with all zoom values so far. I'm not sure how to debug this exactly. Do you have any pointers for me?

**Comment by devTristan** [comment]
What do you mean by "get the geometries around a central point"? Do you have an example of the code you're working with?

**Comment by volkanunsal** [comment]
Yeah, so let's say this is the layer function:

```javascript
app.layer('test_layer', function(tile, render){
  console.log(tile)
  render('SELECT ST_AsGeoJSON(geometry) as the_geom_geojson FROM parcels WHERE ST_Intersects(st_setsrid(geometry, 4326), !bbox_4326!);');
});
```

I am hitting this endpoint:

```
http://localhost:3000/test_layer/10/-74.0059/40.7127.topojson
```

And I expected several geometries to be rendered in the result, but I don't see any. Maybe I'm not using it correctly.

**Comment by devTristan** [comment]
Ah, okay. It's the URL that is't right here. The x and y should be tile numbers, not coordinates. There's an extremely educational page [here](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames) that goes over it.

**Comment by devTristan** [comment]
Here's an example my colleague @wboykinm made a while back that shows how to use topojson tiles: http://bl.ocks.org/wboykinm/7393674

**Comment by volkanunsal** [comment]
I see. So we need to use a converter function or something to go from coordinates to tile numbers? Kinda like this:

```javascript
function long2tile(lon,zoom) { return (Math.floor((lon+180)/360*Math.pow(2,zoom))); }
```

**Comment by devTristan** [comment]
This library is not intended to serve tiles based on coordinates. It uses the standard tile numbers. If you want to get tile xyz from a set of coordinates, those functions will do it. Are you trying to serve tiles to a map?

**Comment by volkanunsal** [comment]
Yeah, exactly.

**Comment by devTristan** [comment]
Okay, which map library are you using? Leaflet, openlayers, etc?

**Comment by volkanunsal** [comment]
Leaflet. I think I might use a Canvas layer to render this. The GeoJSON layer is too slow.

**Comment by wboykinm** [comment]
@volkanunsal Mapzen [has collected a bunch of rendering examples](https://mapzen.com/projects/vector-tiles), including our Hoverboard Canvas renderer. One of those should do the trick for you.

**Comment by volkanunsal** [comment]
@wboykinm Thanks for the tip. I think I might just implement it myself, you know, for science.

**Comment by wboykinm** [comment]
![science](https://cloud.githubusercontent.com/assets/735463/9112210/39dfb96c-3c1b-11e5-8467-816004d7d62e.gif)
