### ISSUE TITLE
Render numeric values

### ISSUE THREAD

**Issue by fxi** [faradayio/tilesplash#14]
On the client side, I need to filter values by numeric comparison with mapbox gl js.

When rendering mvt, numeric values in properties are converted to string. What is the best way to avoid this ?

I've tried to set a node-pg-type parser directly in my application:

```js
var types = require('pg').types;
types.setTypeParser(20, function(val) {
  return parseInt(val)
})
```

It seems to do the job.. But i'ts quite annoying to get the right parser for each OID. Is there a better solution ?

I also tried this, inside stringifyProtobuf :

```js
function filterNum(key, value) {
/* skip arrays (e.g. coordinates)*/
  if( isNaN( parseInt( key ) ) && Object.prototype.toString.call( value ) !== '[object Array]'){
    var vFloat = parseFloat( value );
    if ( ! isNaN( vFloat ) ) {
      return vFloat;
    }
  }
  return value;
}

for ( var layerName in layers ) {
  var jsonString = JSON.stringify( layers[layerName], filterNum )
    vtile.addGeoJSON( jsonString, layerName );
}
```

It's less clean, but maybe more robust ..

**Comment by devTristan** [comment]
Hi @fxi,

Try casting your number(s) to something that can be losslessly casted to Number, like int.

```sql
SELECT x::int FROM -- etc
```

If that doesn't work, your pg-types solution is what I would go with.

**Comment by fxi** [comment]
Thanks !
