### ISSUE TITLE
EventEmitter possible memory leak

### ISSUE THREAD

**Issue by fxi** [faradayio/tilesplash#15]
Hi,

I have an issue with tileplash. After a few queries, this warning is shown and the app seems to slow down a bit.

`warning: possible EventEmitter memory leak detected. 11 timeout listeners added. Use emitter.setMaxListeners() to increase limit.`

I have no idea how to handle this. Any idea ? 

I have a small middleware:
```{js}
midWar = function(req, res, tile, next){
 /*  setHeader */
  res.header( {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept',
    'Cache-Control': 'public, max-age=3600'
  });
  /*  add query string parameters to tile */
  for(var q in req.query){
    val = req.query[q];
    tile[q] = val;
  }
  next();
};
```
A sql template : 

```{js}
var sqlIntersect = dot.template(
    " SELECT ST_AsGeoJSON(ST_SimplifyPreserveTopology({{=it.geom}},(select (1000/(256*2^{{=it.z}})))),3) as the_geom_geojson, " +
    " {{=it.variables}} " +
    " FROM  {{=it.layer}} " +
    " WHERE {{=it.geom}} && !bbox_4326! " +
    " AND ST_Intersects( {{=it.geom}}, !bbox_4326!)" +
    " AND exists (" +
    " select test from users where key='{{=it.key}}' and id={{=it.id}}" +
    ")"
    );
```

And a basic application:

```{js}
 app.layer('tile', midWar, function(tile, render){
  if( ! tile.t || !tile.v || !tile.l || !tile.u ){
    render.empty();
  }
  /* store available layers */
  var sql = sqlIntersect({
    variables: tile.v,
    layer: tile.l, 
    geom: "geom",
    key : tile.t,
    id : tile.u,
    z : tile.z
  });
  layers[tile.l] = sql ;
  render( layers );
});

app.cache(function(tile){
  return tile.x + ':' + tile.y + ':' + tile.z + ':' + tile.l + ':' + tile.v + ':' + tile.t;
}, 1000 * 60 * 60 * 24 * 30); //ttl 30 days ```


Thanks !

**Comment by fxi** [comment]
What a moron.

Sorry for this. 

I've was storing the layer query inside an object named "layers", declared outside the tileplash object. In my script, the new requested layer comes from the request parameters and the keys of the object "layers" are the name of the requested layers. At each new request, tilesplash was rendering all the old layers + the new layer.  Declaring the layers object inside the app.layer callback solved my issue : only the requested layer is rendering now.

Thanks again !

**Comment by devTristan** [comment]
Well, I'm glad you figured it out, because I was at a loss!

**Comment by fxi** [comment]
Yeah, I'm glad too: the thing I'm working on is demoed online today. You were at a loss ? Meaning my gibberish was not clear or it could have been something difficult to probe or reproduce ? Speaking of probe and things, I did not fully understood (at all) the instrument parameter. What goes there ?

Thanks :)

**Comment by devTristan** [comment]
I was at a loss as to where the memory leak was coming from.

You can leave the instrument parameter out. It's for measuring the amount of time different parts of the tile generation process take.

**Comment by fxi** [comment]
Yes, this part of the instrument parameter description is written in the comments and this is why i'm interested :) As I may have to do some benchmarking in the future, this could be the way to do such thing. This parameters seems to take a function that will do something with the output of the timing reported by the tracing function at each 4 main parts. Am I wrong ? 

If you could provide a small example, it would be nice ! If you can't, no problemo, there is still the world wild web to explore.

Thanks

**Comment by devTristan** [comment]
Try something like this:

```js
var app = new Tilesplash('postgres://username@localhost/db_name', null, {}, {
  runQuery: function (ms) {
    console.log('ran sql in ' + ms + 'ms')
  }
});
```

**Comment by fxi** [comment]
Thanks so much for this example ! 

That's incredible. That's so cool. I can monitor main parts of the process. 

```{js}
App 23256 stdout: ran sql in 2.674747ms
App 23256 stdout: got tile in 3.902771ms
App 23256 stdout: ran sql in 2.545834ms
App 23256 stdout: got tile in 5.698789ms
```

Thanks for everything :)

**Comment by devTristan** [comment]
No problem, enjoy using tilesplash.
