### ISSUE TITLE
Doesn't build on newer or older versions of nodejs other than LTS 4 - add to docs?

### ISSUE THREAD

**Issue by shongololo** [faradayio/tilesplash#17]
Trying to install tilesplash I ran into a bunch of issues (mapnik related). The issues were resolved using nodejs LTS 4.x

Perhaps add a note to the docs?

**Comment by wboykinm** [comment]
@shongololo I think you caught this old gem: https://github.com/faradayio/tilesplash/issues/18 - just resolved by the node-mapnik upgrade.
