### ISSUE TITLE
Mapnik 3.5.13 update incompatible

### ISSUE THREAD

**Issue by wboykinm** [faradayio/tilesplash#18]
Following up on #2 - I bumped tilesplash to `node-mapnik` 3.5.13 and ran headlong into [a known bug](https://github.com/mapnik/node-mapnik/issues/674). Will try again on Ubuntu; it might just be OSX weirdness.

**Comment by wboykinm** [comment]
Punted for now by running mapnik v 3.4.19, which keeps us locked to node v4.5 for now: #19

**Comment by abenrob** [comment]
[v3.5.14](https://github.com/mapnik/node-mapnik/blob/master/CHANGELOG.md#3514) is released, opening up v6.x feasibility again. Suggested re-opening of this issue.

**Comment by wboykinm** [comment]
@abenrob Awesome - will take a look.

**Comment by wboykinm** [comment]
https://github.com/faradayio/tilesplash/pull/20

**Comment by wboykinm** [comment]
@abenrob All good here. Use 2.0.4 now. Thanks for the heads up!

**Comment by glw** [comment]
Hi Im still getting install errors using the latest version of nodejs (6.x). I then tried again using version 4.5 and it worked with one small hiccup - I needed to install pug rather than jade.
