### ISSUE TITLE
No ability to configure mapnik simplifiction

### ISSUE THREAD

**Issue by abenrob** [faradayio/tilesplash#22]
mvt tiles present with big holes.
![toronto_z9](https://cloud.githubusercontent.com/assets/3422185/19420121/3d270576-93e5-11e6-975d-98b03104db5c.png)

[mapnik](http://mapnik.org/documentation/node-mapnik/3.5/#VectorTile.addGeoJSON) can control the simplification, in the case here, in the addGeoJson method, but there is no way to provide these options to the layer function.

In my case, hard-coding `{ simplify_distance: 7 }` into the tilesplash source (`vtile.addGeoJSON(JSON.stringify(layers[layerName]), layerName, { simplify_distance: 7 });`) fixes the problem, but is not configurable.

PR incoming, but will need review (attn: @devTristan) as my solution is dependent on the arguments object of Tilesplash.prototype.layer, and works for my use case, but could break other stuff...

The code could use some commenting - there is a lot going on in there, and I'm not sure what is being used by what and when without comments, docs or tests.

**Comment by abenrob** [comment]
Is this project supported?

**Comment by devTristan** [comment]
Hey! Sorry, didn't see this before. This project is somewhat supported. Like you said, the code is messy, needs comments, docs, tests, etc. Eventually I'm planning on putting out a 3.0 which should address these problems, but in the meantime, would you mind updating your PR to include documentation for your changes, as well as a minor version bump?

**Comment by abenrob** [comment]
Sure thing.

**Comment by abenrob** [comment]
From #23, we can now pass mvyOptions as the last (pre-callback) parameter.
For example:
```
app.layer(layer.endpointname, mySpecialMiddleware, { simplify_distance: 7 }, function(tile, render){
    render({
        mylayer: sqlBuildFunction(layer)
    });
});
```
