### ISSUE TITLE
Example for adding feature properties described by PostGIS?

### ISSUE THREAD

**Issue by mngyng** [faradayio/tilesplash#30]
I'm thinking it would be great if the .mvt/.topojson output includes feature properties, so the client side would be able to color the map according to the properties of the polygon (e.g., population).
I'm so far successful in drawing polygon frames via Leaflet.Vectorgrid using the .mvt's generated by Tilesplash, but then I do not know which variable in tilesplash correspond to the property in GeoJSON. Like, the_geom_geojson would correspond to the geometry, but what can I do if I want my .mvt's also contain the properties in geojson according to their PostGIS storage?

**Comment by devTristan** [comment]
Like this!

```sql
SELECT
  id,
  population,
  ST_AsGeoJSON(the_geom) AS the_geom_geojson
FROM places
```

**Comment by mngyng** [comment]
That works! Actually I did that already but made a stupid mistake in variable capitalization in the front end code. The entire line of code is as follows:
`tilesplash.layer('layer_table', userMiddleware, function(tile, render){
  render('SELECT id, property1, ST_AsGeoJSON(the_geom) as the_geom_geojson FROM layer_table WHERE ST_Intersects(the_geom, !bbox_4326!)');
});
`
