### ISSUE TITLE
Hard to guess default layer name inside an .mvt tile

### ISSUE THREAD

**Issue by kachkaev** [faradayio/tilesplash#39]
My colleague and I spent a couple of hours trying to render tilesplash tiles with mapbox-gl. As it turned out, we did not guess the `"layer-name"` inside `.mvt` correctly, so despite that the tiles were reaching the client, the were not picked by Web GL.

Only after I scanned through the source code, I discovered that the default layer name inside `.mvt`s is actually `vectile`. So rendering the following ‘single-layer’ layer and ‘multi-layer’ layer is the same thing:

```js
app.layer('singleLayer', function(tile, render){
  render('SELECT ...');
});

app.layer('multiLayer', function(tile, render){
  render({
    vectile: 'SELECT ...',
  });
});
```

It'd be great if `vectile` as a layer name inside `.mvt` was mentioned in README. I can submit a PR if the idea is approved in general, but I don't mind if someone else does it too.

**Comment by devTristan** [comment]
Hey! You're right, this is confusing. If you send me a PR to update the README, I'd be happy to merge it.

**Comment by kachkaev** [comment]
Done! See #40 :–)
