### ISSUE TITLE
Object.keys called on non-object

### ISSUE THREAD

**Issue by volkanunsal** [faradayio/tilesplash#9]
Trying the example on the README, I ran into this error:

```javascript
var Tilesplash = require('tilesplash');
var app = new Tilesplash('postgis://postgres:@localhost:5432/dev');
```

```
  Object.keys(_dbOptions).forEach(function(key){
         ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
```

Looks like pgMiddleware is expecting an object, and doesn't want to accept a database connection string.

**Comment by devTristan** [comment]
My bad. [1.9.2](https://github.com/faradayio/tilesplash/commit/8ff683adf5e41ca24ccb84c02377e3f95d2f0a96) should fix your problem.
